version: '3'

services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile

    # Enable privileged mode to allow full host access (GPU usage, etc.).
    privileged: true

    # NVIDIA GPU environment variables for compute access.
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    # Volumes, including your project folder. 
    # The entire host is on an SSD NVE, so no special path needed beyond normal volume bindings.
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock 
      - ../..:/workspaces:cached

    # Overrides default command so the container stays running.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

    # Uncomment the next four lines if you will use ptrace-based debuggers (C++, Go, Rust, etc.):
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Use "forwardPorts" in devcontainer.json to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)