# filepath: c:\Projects\autogen\.devcontainer\docker-compose.yml
version: '3.8'

services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1

    # Resource limits and GPU configuration
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
          cpus: '2'
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute, utility]
              options:
                driver.install: false
    
    # GPU runtime configuration
    runtime: ${GPU_RUNTIME:-runc}
    
    volumes:
      # Docker socket passthrough
      - /var/run/docker.sock:/var/run/docker-host.sock
      # Project mount with optimized performance
      - ../..:/workspaces:cached
      # Persistent cache volumes for faster startup
      - autogen-deps:/root/.cache:delegated
      - dotnet-packages:/root/.nuget/packages:delegated
      - python-pip-cache:/root/.cache/pip:delegated
      - vscode-server:/root/.vscode-server:delegated
    
    # Container lifecycle
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    
    # Environment variables for performance
    environment:
      - DOTNET_EnableDiagnostics=0
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONFAULTHANDLER=1
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      # GPU passthrough variables
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-compute,utility}
    
    # Health check for startup monitoring
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/container-ready"]
      interval: 2s
      timeout: 1s
      retries: 30
      start_period: 5s
    
    # Network and debugging options
    network_mode: ${NETWORK_MODE:-bridge}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined

# Persistent volumes for faster subsequent container creations
volumes:
  autogen-deps:
    driver: local
  dotnet-packages:
    driver: local
  python-pip-cache:
    driver: local
  vscode-server:
    driver: local
